#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

if [[ $DISTRO_NAME = "centos" || $DISTRO_NAME = "rhel" || $DISTRO_NAME = "centos7" || $DISTRO_NAME = "rhel7" ]]; then
    if [[ -f "/etc/sysconfig/network-scripts/ifcfg-eth0" ]]; then
	rm -f /etc/sysconfig/network-scripts/ifcfg-eth0
    fi
fi
